name=Arduino_GigaDisplay_GFX
version=1.2.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Adafruit GFX library wrapper for the Arduino GIGA Display Shield.
paragraph=Allows drawing shapes, rendering graphics, and displaying text with configurable fonts on the GIGA Display Shield using the Adafruit GFX core.
category=Display
url=https://docs.arduino.cc/tutorials/giga-display-shield/gfx-guide
architectures=mbed_giga,zephyr_main
includes=Arduino_GigaDisplay_GFX.h
depends=Adafruit GFX Library
